spring:
  application:
     name: verify-service
  data:
    rest:
      detection-strategy: annotated
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jackson:
    serialization:
      write-dates-as-timestamps: true
server:
#  port: 8084
#  servlet:
#    contextPath: /api
